version: "2"

services:
  namenode:
    image: cloudwiz/hadoop-namenode:2.7.7
    container_name: namenode
    hostname: namenode
    restart: always
    volumes:
    - ${WORK_PATH}/data/hadoop/dfs/name:/hadoop/dfs/name
    - ${WORK_PATH}/logs/hadoop/:${WORK_PATH}/hadoop-2.7.7/logs
    environment:
    - CLUSTER_NAME=prod
    env_file:
    - ./hadoop.env
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.2
    logging:
      driver: none
      options:
        max-size: 50m

  datanode:
    image: cloudwiz/hadoop-datanode:2.7.7
    container_name: datanode
    hostname: datanode
    restart: always
    volumes:
    - ${WORK_PATH}/data/hadoop/dfs/data:/hadoop/dfs/data
    - ${WORK_PATH}/logs/hadoop/:${WORK_PATH}/hadoop-2.7.7/logs
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
    - ./hadoop.env
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.3
    depends_on:
    - namenode
    logging:
      driver: none
      options:
        max-size: 50m

  zookeeper:
    image: zookeeper:3.4.10
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=172.19.0.4:2888:3888
    volumes:
    - ${WORK_PATH}/data/zookeeper/:/data
    - ${WORK_PATH}/data/zookeeper/datalog:/datalog
    - ${WORK_PATH}/logs/zookeeper:/logs/zookeeper.log
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.4
    logging:
      driver: none
      options:
        max-size: 50m

  hbase-master:
    image: cloudwiz/hbase-master:1.4.10
    container_name: hbase-master
    hostname: hbase-master
    restart: always
    env_file:
    - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181"
    volumes:
    - ${WORK_PATH}/logs/hadoop/:${WORK_PATH}/hbase-1.4.10/logs
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.5
    depends_on:
    - namenode
    - datanode
    - zookeeper
    logging:
      driver: none
      options:
        max-size: 50m

  hbase-regionserver:
    image: cloudwiz/hbase-regionserver:1.4.10
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    restart: always
    env_file:
    - ./hadoop.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-regionserver
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181 hbase-master:16010"
    volumes:
    - ${WORK_PATH}/logs/hadoop/:${WORK_PATH}/hbase-1.4.10/logs
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.6
    depends_on:
    - namenode
    - datanode
    - zookeeper
    - hbase-master
    logging:
      driver: none
      options:
        max-size: 50m

  mysql-server:
    image: cloudwiz/mysql:5.7.28
    container_name: mysql-server
    restart: always
    volumes:
    - ${WORK_PATH}/tools/mysql/sql/:/sql
    - ${WORK_PATH}/data/mysql/:/var/lib/mysql
    - ${WORK_PATH}/logs/mysql/:/var/log/mysql
    - ${WORK_PATH}/data/binlog/:/logs/binlog
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.7
    logging:
      driver: none
      options:
        max-size: 50m

  elasticsearch:
    image: elasticsearch:5.4.3
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    env_file:
    - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181 hbase-master:16010"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
    - ${WORK_PATH}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - ${WORK_PATH}/data/elasticsearch/:/usr/share/elasticsearch/data/
    - ${WORK_PATH}/logs/elasticsearch/:/usr/share/elasticsearch/logs
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.8
    logging:
      driver: none
      options:
        max-size: 50m

  nginx:
    image: nginx:1.16.1
    container_name: nginx
    hostname: nginx
    restart: always
    env_file:
    - ./hadoop.env
    volumes:
    - ${WORK_PATH}/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - ${WORK_PATH}/nginx/:${WORK_PATH}/nginx/
    - ${WORK_PATH}/logs/nginx/:${WORK_PATH}/logs/nginx/
    - ${WORK_PATH}/certs/:${WORK_PATH}/certs/
    ports:
    - 443:443
    - 5044:5044
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.9
    extra_hosts:
      namenode: 172.19.0.2
      datanode: 172.19.0.3
      zookeeper: 172.19.0.4
      hbase-master: 172.19.0.5
      hbase-regionserver: 172.19.0.6
      mysql-server: 172.19.0.7
      elasticsearch: 172.19.0.8
      nginx: 172.19.0.9
      kafka: 172.19.0.10
      metric-proxy: 172.19.0.11
      opentsdb: 172.19.0.12
      cmservice: 172.19.0.13
      log_processor: 172.19.0.14
      webfront: 172.19.0.15
      cloudwiz_user: 172.19.0.16
      permission: 172.19.0.17
      log_analysis: 172.19.0.18
      chartservice: 172.19.0.19
      log_pp: 172.19.0.20
      alertd: 172.19.0.22
      umanage: 172.19.0.23
      python_daemon: 172.19.0.25
      #### No such service now
      oneagent: 172.19.0.21
      hbase_thrift: 172.19.0.233
    depends_on:
    - mysql-server
    logging:
      driver: local
      options:
        max-size: 50m

  kafka:
    image: wurstmeister/kafka:2.11-1.0.2
    container_name: kafka
    hostname: kafka
    restart: always
    env_file:
    - ./hadoop.env
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.10
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M" 
    volumes:
    - ${WORK_PATH}/data/kafka/:/kafka/kafka-logs-kafka/
    - ${WORK_PATH}/logs/kafka/:/opt/kafka_2.11-1.0.2/logs
    depends_on:
    - zookeeper
    logging:
      driver: none
      options:
        max-size: 50m

  metric-proxy:
    image: cloudwiz/metric-proxy:1.0.4
    container_name: metric-proxy
    hostname: metric-proxy
    restart: always
    env_file:
    - ./hadoop.env
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.11
    volumes:
    - ${WORK_PATH}/startup/envs.sh:${WORK_PATH}/startup/envs.sh
    - ${WORK_PATH}/metric-proxy/bin/start.sh:${WORK_PATH}/metric-proxy/bin/start.sh
    - ${WORK_PATH}/metric-proxy/config/application.yml:${WORK_PATH}/metric-proxy/config/application.yml
    - ${WORK_PATH}/metric-proxy/config/log4j.properties:${WORK_PATH}/metric-proxy/config/log4j.properties
    - ${WORK_PATH}/logs/metric-proxy/:${WORK_PATH}/logs/metric-proxy/
    - ${WORK_PATH}/certs/nginx/:${WORK_PATH}/certs/nginx/
    - ${WORK_PATH}/certs/metric-proxy/:${WORK_PATH}/certs/metric-proxy/
    depends_on:
    - kafka
    logging:
      driver: none
      options:
        max-size: 50m

  opentsdb:
    image: cloudwiz/opentsdb:2.3.0
    container_name: opentsdb
    hostname: opentsdb
    restart: always
    env_file:
    - ./hadoop.env
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.12
    volumes:
    - ${WORK_PATH}/startup/envs.sh:${WORK_PATH}/startup/envs.sh
    - ${WORK_PATH}/opentsdb/bin/start.sh:${WORK_PATH}/opentsdb/bin/start.sh
    - ${WORK_PATH}/opentsdb/conf/opentsdb.conf:${WORK_PATH}/opentsdb/conf/opentsdb.conf
    - ${WORK_PATH}/opentsdb/conf/logback.xml:${WORK_PATH}/opentsdb/conf/logback.xml
    - ${WORK_PATH}/startup:${WORK_PATH}/startup
    - ${WORK_PATH}/logs/opentsdb/:${WORK_PATH}/logs/opentsdb/
    depends_on:
    - hbase-regionserver
    logging:
      driver: none
      options:
        max-size: 50m

  cmservice:
    image: cloudwiz/cmservice:1.4.2
    container_name: cmservice
    hostname: cmservice
    restart: always
    env_file:
    - ./hadoop.env
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.13
    volumes:
    - ${WORK_PATH}/startup/envs.sh:${WORK_PATH}/startup/envs.sh
    - ${WORK_PATH}/cmservice/bin/start.sh:${WORK_PATH}/cmservice/bin/start.sh
    - ${WORK_PATH}/cmservice/conf/cmservice.properties:${WORK_PATH}/cmservice/conf/cmservice.properties
    - ${WORK_PATH}/cmservice/conf/log4j.properties:${WORK_PATH}/cmservice/conf/log4j.properties
    - ${WORK_PATH}/logs/cmservice/:${WORK_PATH}/logs/cmservice/
    - ${WORK_PATH}/certs/nginx/:${WORK_PATH}/certs/nginx/
    - ${WORK_PATH}/certs/cmservice/:${WORK_PATH}/certs/cmservice/
    depends_on:
    - mysql-server
    logging:
      driver: none
      options:
        max-size: 50m

  log_processor:
    image: cloudwiz/log-processor:1.0.1
    container_name: log_processor
    hostname: log_processor
    restart: always
    env_file:
    - ./hadoop.env
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.14
    volumes:
    - ${WORK_PATH}/startup/envs.sh:${WORK_PATH}/startup/envs.sh
    - ${WORK_PATH}/log-processor/bin/start.sh:${WORK_PATH}/log-processor/bin/start.sh
    - ${WORK_PATH}/log-processor/config/:${WORK_PATH}/log-processor/config/
    - ${WORK_PATH}/logs/log-processor/:${WORK_PATH}/logs/log-processor/
    - ${WORK_PATH}/certs/nginx/:${WORK_PATH}/certs/nginx/
    - ${WORK_PATH}/certs/log-processor/:${WORK_PATH}/certs/log-processor/
    depends_on:
    - kafka
    - elasticsearch
    logging:
      driver: none
      options:
        max-size: 50m

  webfront:
    image: cloudwiz/webfront:3.5.10
    container_name: webfront
    hostname: webfront
    restart: always
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.15
    volumes:
    #- /tmp/webfront:${WORK_PATH}/webfront
    - ${WORK_PATH}/webfront/conf/defaults.ini:${WORK_PATH}/webfront/conf/defaults.ini
    - ${WORK_PATH}/logs/webfront/:${WORK_PATH}/logs/webfront
    - ${WORK_PATH}/certs/nginx/:${WORK_PATH}/certs/nginx/
    - ${WORK_PATH}/certs/webfront/:${WORK_PATH}/certs/webfront/
    depends_on:
    - mysql-server
    logging:
      driver: local
      options:
        max-size: 50m

#  cloudwiz_user:
#    image: cloudwiz/cloudwiz-user:1.1.7
#    container_name: cloudwiz_user
#    hostname: cloudwiz_user
#    restart: always
#    networks:
#      cwiz_network:
#        ipv4_address: 172.19.0.16
#    volumes:
#    - ${WORK_PATH}/cloudwiz-user/web.config.js:${WORK_PATH}/cloudwiz-user/web.config.js
#    - ${WORK_PATH}/certs/nginx/:${WORK_PATH}/certs/nginx/
#    - ${WORK_PATH}/certs/cloudwiz-user/:${WORK_PATH}/certs/cloudwiz-user/
#    depends_on:
#    - permission

  permission:
    image: cloudwiz/permission:1.0.10
    container_name: permission
    hostname: permission
    restart: always
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.17
    volumes:
    - ${WORK_PATH}/startup/envs.sh:${WORK_PATH}/startup/envs.sh
    - ${WORK_PATH}/permission/bin/start.sh:${WORK_PATH}/permission/bin/start.sh
    - ${WORK_PATH}/permission/config/application.yml:${WORK_PATH}/permission/config/application.yml
    - ${WORK_PATH}/permission/config/log4j2.yml:${WORK_PATH}/permission/config/log4j2.yml
    - ${WORK_PATH}/logs/permission/:${WORK_PATH}/logs/permission
    - ${WORK_PATH}/certs/nginx/:${WORK_PATH}/certs/nginx/
    - ${WORK_PATH}/certs/permission/:${WORK_PATH}/certs/permission/
    depends_on:
    - mysql-server
    - webfront
    logging:
      driver: none
      options:
        max-size: 50m

  log_analysis:
    image: cloudwiz/log-analysis:1.0.3
    container_name: log_analysis
    hostname: log_analysis
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.18
    volumes:
    - ${WORK_PATH}/startup/envs.sh:${WORK_PATH}/startup/envs.sh
    - ${WORK_PATH}/log-analysis/bin/start.sh:${WORK_PATH}/log-analysis/bin/start.sh
    - ${WORK_PATH}/log-analysis/config/log.analysis.properties:${WORK_PATH}/log-analysis/config/log.analysis.properties
    - ${WORK_PATH}/log-analysis/config/log4j.properties:${WORK_PATH}/log-analysis/config/log4j.properties
    - ${WORK_PATH}/logs/log-analysis/:${WORK_PATH}/logs/log-analysis/
    - ${WORK_PATH}/certs/nginx/:${WORK_PATH}/certs/nginx/
    - ${WORK_PATH}/certs/log-analysis/:${WORK_PATH}/certs/log-analysis/
    depends_on:
    - mysql-server
    logging:
      driver: none
      options:
        max-size: 50m

  chartservice:
    image: cloudwiz/chartservice:1.0.0
    container_name: chartservice
    hostname: chartservice
    restart: always
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.19
    volumes:
    - ${WORK_PATH}/startup/envs.sh:${WORK_PATH}/startup/envs.sh
    - ${WORK_PATH}/chartservice/bin/start.sh:${WORK_PATH}/chartservice/bin/start.sh
    - ${WORK_PATH}/chartservice/conf/chartservice.properties:${WORK_PATH}/chartservice/conf/chartservice.properties
    - ${WORK_PATH}/chartservice/conf/log4j.properties:${WORK_PATH}/chartservice/conf/log4j.properties
    - ${WORK_PATH}/report_tmp/:${WORK_PATH}/report_tmp/
    - ${WORK_PATH}/logs/chartservice/:${WORK_PATH}/logs/chartservice/
    logging:
      driver: none
      options:
        max-size: 50m

  log_pp:
    image: cloudwiz/log-pp:1.0.1
    container_name: log_pp
    hostname: log_pp
    restart: always
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.20
    volumes:
    - ${WORK_PATH}/startup/envs.sh:${WORK_PATH}/startup/envs.sh
    - ${WORK_PATH}/log-pp/bin/start.sh:${WORK_PATH}/log-pp/bin/start.sh
    - ${WORK_PATH}/log-pp/config/log.pp.properties:${WORK_PATH}/log-pp/config/log.pp.properties
    - ${WORK_PATH}/log-pp/config/log4j.properties:${WORK_PATH}/log-pp/config/log4j.properties
    - ${WORK_PATH}/log-pp/config/patterns/:${WORK_PATH}/log-pp/config/patterns/
    - ${WORK_PATH}/logs/log-pp/:${WORK_PATH}/logs/log-pp/
    - ${WORK_PATH}/certs/nginx/:${WORK_PATH}/certs/nginx/
    - ${WORK_PATH}/certs/log-pp/:${WORK_PATH}/certs/log-pp/
    depends_on:
    - kafka
    - opentsdb
    logging:
      driver: none
      options:
        max-size: 50m

  alertd:
    image: cloudwiz/alertd:1.1.13
    container_name: alertd
    hostname: alertd
    restart: always
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.22
    volumes:
    - ${WORK_PATH}/startup/envs.sh:${WORK_PATH}/startup/envs.sh
    - ${WORK_PATH}/alertd/bin/start.sh:${WORK_PATH}/alertd/bin/start.sh
    - ${WORK_PATH}/alertd/conf/:${WORK_PATH}/alertd/conf/
    - ${WORK_PATH}/report_tmp/:${WORK_PATH}/report_tmp/
    - ${WORK_PATH}/logs/alertd/:${WORK_PATH}/logs/alertd/
    - ${WORK_PATH}/certs/nginx/:${WORK_PATH}/certs/nginx/
    - ${WORK_PATH}/certs/alertd/:${WORK_PATH}/certs/alertd/
    depends_on:
    - mysql-server
    - namenode
    - opentsdb
    logging:
      driver: none
      options:
        max-size: 50m

#  umanager:
#    image: cloudwiz/umanager:1.0.0
#    container_name: umanager
#    hostname: umanager
#    restart: always
#    networks:
#      cwiz_network:
#        ipv4_address: 172.19.0.23
#    volumes:
#    - ${WORK_PATH}/umanager/:${WORK_PATH}/umanager/
#    - ${WORK_PATH}/nginx/download/release/singles/:${WORK_PATH}/nginx/download/release/singles/
#    - ${WORK_PATH}/logs/umanager/:${WORK_PATH}/logs/umanager/
#    depends_on:
#    - mysql-server

volumes:
  hadoop_namenode: 
  hadoop_datanode: 
  elasticsearch:
  zookeeper:
  nginx:
  kafka:

networks:
  cwiz_network:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/24"
