version: "3"

services:
  namenode:
    image: cloudwiz/hadoop-namenode
    container_name: namenode
    hostname: namenode
    volumes:
    - ${WORK_PATH}/data/hadoop/dfs/name:/hadoop/dfs/name
    environment:
    - CLUSTER_NAME=prod
    env_file:
    - ./hadoop.env
    ports:
    - 50070:50070
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.2

  datanode:
    image: cloudwiz/hadoop-datanode
    container_name: datanode
    hostname: datanode
    volumes:
    - ${WORK_PATH}/data/hadoop/dfs/data:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
    - ./hadoop.env
    ports:
    - 50075:50075
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.3
    depends_on:
    - namenode

  zookeeper:
    image: zookeeper:3.4.10
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
    - 2181:2181
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.4

  hbase-master:
    image: cloudwiz/hbase-master
    container_name: hbase-master
    hostname: hbase-master
    env_file:
    - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181"
    ports:
    - 16010:16010
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.5
    depends_on:
    - namenode
    - datanode
    - zookeeper

  hbase-regionserver:
    image: cloudwiz/hbase-regionserver
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    env_file:
    - ./hadoop.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-regionserver
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181 hbase-master:16010"
    ports:
    - 16030:16030
    - 16020:16020
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.6
    depends_on:
    - namenode
    - datanode
    - zookeeper
    - hbase-master

  mysql-server:
    image: cloudwiz/mysql
    container_name: mysql-server
    volumes:
    - ${WORK_PATH}/tools/mysql/sql/:/sql
    - ${WORK_PATH}/logs/mysql/:/var/log/mysql/
    #- /usr/local/docker/mysql/conf/my.cnf:/etc/mysql/my.cnf
    #- /usr/local/docker/mysql/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.7

  elasticsearch:
    image: elasticsearch:5.4.3
    container_name: elasticsearch
    hostname: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    env_file:
    - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181 hbase-master:16010"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
    - ${WORK_PATH}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - ${WORK_PATH}/data/elasticsearch/:/usr/share/elasticsearch/data/
    - ${WORK_PATH}/logs/elasticsearch/:/usr/share/elasticsearch/logs
    ports:
    - 9200:9200
    - 9300:9300
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.8

  nginx:
    image: nginx:1.12.1
    container_name: nginx
    hostname: nginx
    env_file:
    - ./hadoop.env
    volumes:
    - ${WORK_PATH}/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - ${WORK_PATH}/nginx/:/opt/nginx/
    - ${WORK_PATH}/logs/nginx/:/log/nginx/
    #- ${WORK_PATH}/logs/nginx/access.log:/log/nginx/access.log
    #- ${WORK_PATH}/logs/nginx/error.log:/log/nginx/error.log
    ports:
    - 8080:8080
    - 80:80
    - 443:443
    - 5044:5044
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.9
    extra_hosts:
      namenode: 172.19.0.2
      datanode: 172.19.0.3
      zookeeper: 172.19.0.4
      hbase-master: 172.19.0.5
      hbase-regionserver: 172.19.0.6
      mysql-server: 172.19.0.7
      elasticsearch: 172.19.0.8
      nginx: 172.19.0.9
      kafka: 172.19.0.10
      metric-proxy: 172.19.0.11
      opentsdb: 172.19.0.12
      cmservice: 172.19.0.13
      log_processor: 172.19.0.14
      webfront: 172.19.0.15
      cloudwiz_user: 172.19.0.16
      permission: 172.19.0.17
      log_analysis: 172.19.0.18
      chartservice: 172.19.0.19
      log_pp: 172.19.0.20
      oneagent: 172.19.0.21
      alertd: 172.19.0.22
      umanage: 172.19.0.23
      #### No such service now 
      python_daemon: 172.19.0.222
      hbase_thrift: 172.19.0.233
    depends_on:
    - mysql-server

  kafka:
    image: wurstmeister/kafka:2.11-1.0.2
    container_name: kafka
    hostname: kafka
    env_file:
    - ./hadoop.env
    ports:
    - 9092:9092
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.10
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M" 
#    volumes:
#    - kafka:/var/run/docker.sock
    volumes:
    - ${WORK_PATH}/logs/kafka/:/opt/kafka/logs/
    depends_on:
    - zookeeper

  metric-proxy:
    image: cloudwiz/metric-proxy
    container_name: metric-proxy
    hostname: metric-proxy
    env_file:
    - ./hadoop.env
    ports:
    - 4243:4243
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.11
    volumes:
    - ${WORK_PATH}/startup/envs.sh:/opt/startup/envs.sh
    - ${WORK_PATH}/metric-proxy/bin/start.sh:/opt/metric-proxy/bin/start.sh
    - ${WORK_PATH}/metric-proxy/config/application.yml:/opt/metric-proxy/config/application.yml
    - ${WORK_PATH}/metric-proxy/config/log4j.properties:/opt/metric-proxy/config/log4j.properties
    - ${WORK_PATH}/logs/metric-proxy/:/log/metric-proxy/
    depends_on:
    - kafka

  opentsdb:
    image: cloudwiz/opentsdb
    container_name: opentsdb
    hostname: opentsdb
    env_file:
    - ./hadoop.env
    ports:
    - 4242:4242
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.12
    volumes:
    - ${WORK_PATH}/startup/envs.sh:/opt/startup/envs.sh
    - ${WORK_PATH}/opentsdb/bin/start.sh:/opt/opentsdb/bin/start.sh
    - ${WORK_PATH}/opentsdb/conf/opentsdb.conf:/opt/opentsdb/conf/opentsdb.conf
    - ${WORK_PATH}/opentsdb/conf/logback.xml:/opt/opentsdb/conf/logback.xml
    - ${WORK_PATH}/logs/opentsdb/:/log/opentsdb/
    - ${WORK_PATH}/startup:/opt/startup
    depends_on:
    - hbase-regionserver

  cmservice:
    image: cloudwiz/cmservice
    container_name: cmservice
    hostname: cmservice
    env_file:
    - ./hadoop.env
    ports:
    - 9601:9601
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.13
    volumes:
    - ${WORK_PATH}/startup/envs.sh:/opt/startup/envs.sh
    - ${WORK_PATH}/cmservice/bin/start.sh:/opt/cmservice/bin/start.sh
    - ${WORK_PATH}/logs/cmservice/:/log/cmservice/
    - ${WORK_PATH}/cmservice/conf/cmservice.properties:/opt/cmservice/conf/cmservice.properties
    - ${WORK_PATH}/cmservice/conf/log4j.properties:/opt/cmservice/conf/log4j.properties
    depends_on:
    - mysql-server

  log_processor:
    image: cloudwiz/log-processor
    container_name: log-processor
    hostname: log-processor
    env_file:
    - ./hadoop.env
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.14
    volumes:
    - ${WORK_PATH}/startup/envs.sh:/opt/startup/envs.sh
    - ${WORK_PATH}/log-processor/bin/start.sh:/opt/log-processor/bin/start.sh
    - ${WORK_PATH}/log-processor/config/:/opt/log-processor/config/
    - ${WORK_PATH}/logs/log-processor/:/log/log-processor/
    depends_on:
    - kafka
    - elasticsearch

  webfront:
    image: cloudwiz/webfront
    container_name: webfront
    hostname: webfront
    ports:
    - 3000:3000
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.15
    volumes:
    - ${WORK_PATH}/webfront/conf/defaults.ini:/opt/webfront/conf/defaults.ini
    - ${WORK_PATH}/logs/webfront/:/log/
    depends_on:
    - mysql-server

  cloudwiz_user:
    image: cloudwiz/cloudwiz-user
    container_name: cloudwiz-user
    hostname: cloudwiz-user
    ports:
    - 7002:7002
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.16
    volumes:
    - ${WORK_PATH}/cloudwiz-user/web.config.js:/opt/cloudwiz-user/web.config.js
    depends_on:
    - permission

  permission:
    image: cloudwiz/permission
    container_name: permission
    hostname: permission
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.17
    volumes:
    - ${WORK_PATH}/startup/envs.sh:/opt/startup/envs.sh
    - ${WORK_PATH}/permission/bin/start.sh:/opt/permission/bin/start.sh
    - ${WORK_PATH}/permission/config/application.yml:/opt/permission/config/application.yml
    - ${WORK_PATH}/permission/config/log4j2.yml:/opt/permission/config/log4j2.yml
    - ${WORK_PATH}/logs/permission/:/log/
    depends_on:
    - mysql-server
    - webfront

  log_analysis:
    image: cloudwiz/log-analysis
    container_name: log-analysis
    hostname: log-analysis
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.18
    volumes:
    - ${WORK_PATH}/startup/envs.sh:/opt/startup/envs.sh
    - ${WORK_PATH}/log-analysis/bin/start.sh:/opt/log-analysis/bin/start.sh
    - ${WORK_PATH}/log-analysis/config/log.analysis.properties:/opt/log-analysis/config/log.analysis.properties
    - ${WORK_PATH}/log-analysis/config/log4j.properties:/opt/log-analysis/config/log4j.properties
    - ${WORK_PATH}/logs/log-analysis/:/log/log-analysis/
    depends_on:
    - mysql-server

  chartservice:
    image: cloudwiz/chartservice
    container_name: chartservice
    hostname: chartservice
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.19
    volumes:
    - ${WORK_PATH}/startup/envs.sh:/opt/startup/envs.sh
    - ${WORK_PATH}/chartservice/bin/start.sh:/opt/chartservice/bin/start.sh
    - ${WORK_PATH}/chartservice/conf/chartservice.properties:/opt/chartservice/conf/chartservice.properties
    - ${WORK_PATH}/chartservice/conf/log4j.properties:/opt/chartservice/conf/log4j.properties
    - ${WORK_PATH}/logs/chartservice/:/log/chartservice/

  log_pp:
    image: cloudwiz/log-pp
    container_name: log-pp
    hostname: log-pp
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.20
    volumes:
    - ${WORK_PATH}/startup/envs.sh:/opt/startup/envs.sh
    - ${WORK_PATH}/log-pp/bin/start.sh:/opt/log-pp/bin/start.sh
    - ${WORK_PATH}/log-pp/config/log.pp.properties:/opt/log-pp/config/log.pp.properties
    - ${WORK_PATH}/log-pp/config/log4j.properties:/opt/log-pp/config/log4j.properties
    - ${WORK_PATH}/log-pp/config/patterns/:/opt/log-pp/config/patterns/
    - ${WORK_PATH}/logs/log-pp/:/log/log-pp/
    depends_on:
    - kafka
    - opentsdb

  oneagent:
    image: cloudwiz/oneagent
    container_name: oneagent
    hostname: oneagent
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.21
    volumes:
    - ${WORK_PATH}/startup/envs.sh:/opt/startup/envs.sh
    - ${WORK_PATH}/oneagent/bin/start.sh:/opt/oneagent/bin/start.sh
    - ${WORK_PATH}/oneagent/conf/:/opt/oneagent/conf/
    - ${WORK_PATH}/logs/oneagent/:/log/
    depends_on:
    - mysql-server
    - namenode
    - zookeeper
    - kafka

  alertd:
    image: cloudwiz/alertd
    container_name: alertd
    hostname: alertd
    ports:
    - 5001:5001
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.22
    volumes:
    - ${WORK_PATH}/startup/envs.sh:/opt/startup/envs.sh
    - ${WORK_PATH}/alertd/bin/start.sh:/opt/alertd/bin/start.sh
    - ${WORK_PATH}/alertd/conf/:/opt/alertd/conf/
    - ${WORK_PATH}/logs/alertd/:/log/alertd/
    depends_on:
    - mysql-server
    - namenode
    - opentsdb

  umanager:
    image: cloudwiz/umanager
    container_name: umanager
    hostname: umanager
    networks:
      cwiz_network:
        ipv4_address: 172.19.0.23
    volumes:
    - ${WORK_PATH}/umanager/:/opt/umanager/
    - ${WORK_PATH}/nginx/download/release/singles/:/opt/nginx/download/release/singles/
    - ${WORK_PATH}/logs/umanager/:/log/umanager/
    depends_on:
    - mysql-server

volumes:
  hadoop_namenode: 
  hadoop_datanode: 
  elasticsearch:
  zookeeper:
  nginx:
  kafka:

networks:
  cwiz_network:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/24"
